### ISSUE TITLE
Integration configuration has two unlabeled slider bars and a checkbox

### ISSUE THREAD

**Issue by mrand** [briis/weatherbit#8] opened 2020-05-29 23:17 UTC
Thanks for working on this integration - I'm looking forward to trying it!   At first I thought it was my theme, but even changing to the default theme doesn't expose any labels.  What do they control?

![image](https://user-images.githubusercontent.com/435987/83312671-d4000380-a1d8-11ea-9b82-2b1146ea6334.png)

**Comment by briis** [comment] 2020-05-30 05:32
Hi,
This is a caching issue. You must have had the previous version installed. I've seen this a few times during development. Try and clear your cache, before installing. It will show correctly after a bit of time.

**Comment by mrand** [comment] 2020-05-30 14:33
I assume you mean browser cache?   This is the first time installing the integration and I've pulled it up on two different computers.  Tried F5, to no effect.

**Comment by mrand** [comment] 2020-05-30 16:08
I should note that I haven't had time to go though the breaking changes, so I am still on 0.108.x.  If this might be due to any of the theming changes in the past two releases, then we can wait a few weeks, when I plan to upgrade to 0.111.

**Comment by briis** [comment] 2020-06-01 05:05
This is really strange. I just double checked the 0.10 files that are downloaded, and all the text and references are in the files that will be downloaded. The version of HA you are running should not make a difference. I cannot reproduce this error on any of my installations.

**Comment by mrand** [comment] 2020-06-01 12:19
I've tried the following:

* Reboot
* Used Chrome inspector - don't see any selectable text items surrounding the bars
* Removed browser_mod
* Upgraded weatherbit
* Reboot again

It said "please wait" while installing the upgraded integration when I went there immediately after that last reboot, but still no other text surrounding things.
I'm willing to help with further debug if I can be of help.

**Comment by briis** [comment] 2020-06-02 06:34
One more thought: Did you do a manual install? If yes, did you remember to copy the files in the `translations` directory? That is were the text definitions are pulled from.

**Comment by briis** [comment] 2020-06-02 06:40
I just managed to get the 'missing text' on an installation. (Running in Chrome Browser). I then  went to the Browser section 'More Tools' and then 'Clear Browsing Data' and marked 'Cached images and Files' and then pressed the button 'Clear data'. I then refreshed the browser on the Home Assistant page and went back to add the Weatherbit integration. I now had the text on the screen as expected.

**Comment by briis** [comment] 2020-06-09 06:56
As there has been no reply on this for more than a week, I assume it has been resolved, so I will close this now. Re-Open if you still have the issue.

**Closed as completed by briis** 2020-06-09 06:56 UTC
