### ISSUE TITLE
There is a deprecation warning with core-2022.7.0b0

### ISSUE THREAD

**Issue by gieljnssns** [briis/weatherbit#72] opened 2022-06-29 23:15 UTC
```
Logger: homeassistant.components.weather
Source: components/weather/__init__.py:308
Integration: Weather (documentation, issues)
First occurred: 01:11:30 (1 occurrences)
Last logged: 01:11:30

custom_components.weatherbit.weather::WeatherbitWeatherEntity is overriding deprecated methods on an instance of WeatherEntity, this is not valid and will be unsupported from Home Assistant 2023.1. Please report it to the custom component author.
```

**Comment by briis** [comment] 2022-06-30 08:19
Duplicate of issue #70. The fix is done, just waiting for the 2022.7 release.

**Closed as completed by briis** 2022-06-30 08:19 UTC
