### ISSUE TITLE
Home Assistant Weather Tile shows off by one day

### ISSUE THREAD

**Issue by MichaelStruck** [briis/weatherbit#64] opened 2022-04-09 05:45 UTC
I have read the comments in the forum after installing this add-on yesterday and I see this was an issue originally (~2020) but I had difficulty really understanding if the fix was on my end or the add on. I ensured my computer and home assistant had the right zone (-7 UTC, Pacific US). However, my weather tile still shows a day behind on the multi-day forecast. I apologize if I missed anything but hopefully the fix is rather easy. Thanks!

edit: Using 1.0.8 if that is needed, installed 4/7/22. I see another issue from 1.0.4 here so I assume this is not fixed?

**Comment by greg520820** [comment] 2022-04-12 21:47
You may want to load version 1.0.5 until the newer versions are fixed.

**Comment by briis** [comment] 2022-04-16 09:36
Just to make sure where the error is:

As I understand it, it is the `weather.weatherbit` entity that shows the wrong date? Is that correct?
What about the `sensor.weatherbit_forecast_day_1`, is that showing the correct date?

**Comment by briis** [comment] 2022-04-16 09:37
This is basically a duplicate of #62.

**Comment by MichaelStruck** [comment] 2022-04-16 14:41
Correct....same as issue 62.

**Comment by greg520820** [comment] 2022-04-16 15:14
Both the weather.weatherbit  and sensor.weatherbit_forecast_day_1 entities have the correct date, but the time stamp is different  after ver. 1.0.5 as described below.  This is causing the displayed forecast to be off by one day. Today it is Saturday, but on versions after 1.0.5 it displays as Friday on dashboard, but the forecast numbers are for Saturday.  

I'm thinking the problem is connected to the change made in version 1.0.6 described as "Fixing forecast date not in right format. Date needs to be a UTC time string and not DateTime object."

Time Stamp Difference between versions after 1.0.5:
"All version after 1.05 the forecast is one day behind, at least for my time zone.

On version 1.05 the entities created for sensor.weatherbit_forecast_day_1 is datetime: '2022-02-23T16:00:00+00:00', but all version after 1.05 the entity is created with a datetime: '2022-02-23T00:00:00+00:00'. I'm in the New York time zone, so the 00 hours minus 5 hours for the time zone correction makes the day 1 forecast header being marked as yesterday."

**Comment by briis** [comment] 2022-04-17 06:33
I have now made a pre-release of 1.0.9-beta.1 which contains a potential fix. I need you to test it out. If you run through HACS, you need Beta releases enabled to see it. I am also closing this issue now, so please continue with your feedback in Issue #62.

**Closed as completed by briis** 2022-04-17 06:33 UTC
