### ISSUE TITLE
LENGTH_MILLIMETERS from `homeassistant.util.unit_conversion` cannot be found.

### ISSUE THREAD

**Issue by jeroenterheerdt** [briis/weatherbit#83] opened 2022-11-04 22:46 UTC
Logger: homeassistant.setup
Source: setup.py:320
First occurred: 3:22:21 PM (1 occurrences)
Last logged: 3:22:21 PM

I am on HA 2022.11.1

Unable to prepare setup for platform weatherbit.sensor: Platform not found (cannot import name 'LENGTH_MILLIMETERS' from 'homeassistant.util.unit_conversion' (/usr/src/homeassistant/homeassistant/util/unit_conversion.py)).

**Comment by briis** [comment] 2022-11-05 04:52
Duplicate of #81. Upgrade to the latest release of the Integration that has the fix.

**Closed as completed by briis** 2022-11-05 04:52 UTC
